# model
#model_name_or_path: /mnt/e/UbuntuFiles/models_saved/Qwen1.5-7B-Chat
#model_name_or_path: /mnt/e/UbuntuFiles/models_saved/Qwen1.5-14B-Chat-GPTQ-Int4
#model_name_or_path: /mnt/d/PycharmProjects/models/Qwen1.5-14B-Chat-GPTQ-Int4
#model_name_or_path: qwen/Qwen-14B-Chat-Int4
#model_name_or_path: qwen/Qwen1.5-14B-Chat-GPTQ-Int4
#model_name_or_path: /root/autodl-tmp/Qwen2-7B-Instruct
#model_name_or_path: qwen/Qwen2-7B-Instruct
#model_name_or_path: /root/autodl-tmp/qwen/Qwen2-7B-Instruct
model_name_or_path: /root/autodl-tmp/qwen/Qwen1_5-14B-Chat-GPTQ-Int4
# method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_target: q_proj,v_proj,k_proj,o_proj,down_proj,up_proj,gate_proj
flash_attn: fa2
sliding_window_attn: true
#print_param_status: true

## ddp
#ddp_timeout: 180000000
#deepspeed: examples/deepspeed/ds_z2_offload_config.json
report_to: wandb

# dataset
#dataset: instruction_only_rag
dataset: instruction_only_rag,dynamic_cot_trigger_rag
template: qwen
cutoff_len: 4096
val_size: 0.03
overwrite_cache: true
preprocessing_num_workers: 16

# output
output_dir: checkpoints/qwen/0620_qwen2_rag_sft_exp4
logging_steps: 5
save_steps: 80
plot_loss: true
overwrite_output_dir: true

# train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 0.00005
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true

# eval
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 30
