# model
#model_name_or_path: /mnt/e/UbuntuFiles/models_saved/Qwen1.5-7B-Chat
#model_name_or_path: /mnt/e/UbuntuFiles/models_saved/Qwen1.5-14B-Chat-GPTQ-Int4
adapter_name_or_path: checkpoints/qwen/0515_qwen_rag_exp1
#model_name_or_path: /mnt/d/PycharmProjects/models/Qwen1.5-14B-Chat-GPTQ-Int4
#model_name_or_path: qwen/Qwen-14B-Chat-Int4
model_name_or_path: qwen/Qwen1.5-14B-Chat-GPTQ-Int4
# method
stage: dpo
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_target: q_proj,v_proj,k_proj,o_proj,down_proj,up_proj,gate_proj
#print_param_status: true

# ddp
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z2_offload_config.json #Zero-3不支持QLoRA
report_to: wandb

# dataset
#dataset: instruction_only_rag
#dataset: debug_rag_comparison
dataset: qwen_rag_comparison
template: qwen
cutoff_len: 3600 # 只有80GB可以跑
#max_samples: 200
#val_size: 0.01
overwrite_cache: true
preprocessing_num_workers: 16

# output
output_dir: checkpoints/qwen/0515_qwen_rag_exp1_dpo
logging_steps: 5
save_steps: 400
plot_loss: true
overwrite_output_dir: true

# train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 0.000005
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true

# eval
#per_device_eval_batch_size: 1
#evaluation_strategy: steps
#eval_steps: 30
