# model
#model_name_or_path: /mnt/e/UbuntuFiles/models_saved/Qwen1.5-14B-Chat-GPTQ-Int4
#model_name_or_path: /mnt/d/PycharmProjects/models/Qwen1.5-14B-Chat-GPTQ-Int4
#model_name_or_path: qwen/Qwen-14B-Chat-Int4
model_name_or_path: qwen/Qwen1.5-14B-Chat-GPTQ-Int4
# method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_target: q_proj,v_proj,k_proj,o_proj,down_proj,up_proj,gate_proj
#print_param_status: true
## ddp
#ddp_timeout: 180000000

# dataset
dataset: instruction_only_rag
template: qwen
cutoff_len: 3200
#max_samples: 200
val_size: 0.1
overwrite_cache: true
preprocessing_num_workers: 16

# output
output_dir: checkpoints/qwen/0513_qwen_rag_exp4
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true

# train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 0.00005
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true

# eval
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 200
